// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDse4uWhtbvvi8-lpMhqyH-9eO83zRWA',
    appId: '1:90431643782:web:18171e4534e92454b3f107',
    messagingSenderId: '90431643782',
    projectId: 'chti-face-book-a983b',
    authDomain: 'chti-face-book-a983b.firebaseapp.com',
    storageBucket: 'chti-face-book-a983b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaROGaIn7Q-XaIlC3B-7ETGqzVyZilbwU',
    appId: '1:90431643782:android:8690b0e85903de93b3f107',
    messagingSenderId: '90431643782',
    projectId: 'chti-face-book-a983b',
    storageBucket: 'chti-face-book-a983b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbnODr26tpiVJ8qvtXF0CICF1rf5K0so',
    appId: '1:90431643782:ios:1ea6be01de06795eb3f107',
    messagingSenderId: '90431643782',
    projectId: 'chti-face-book-a983b',
    storageBucket: 'chti-face-book-a983b.firebasestorage.app',
    iosBundleId: 'com.mobile.projetchtifacebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbnODr26tpiVJ8qvtXF0CICF1rf5K0so',
    appId: '1:90431643782:ios:d2e58f782fae134db3f107',
    messagingSenderId: '90431643782',
    projectId: 'chti-face-book-a983b',
    storageBucket: 'chti-face-book-a983b.firebasestorage.app',
    iosBundleId: 'com.example.td1MaPremiereApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApDse4uWhtbvvi8-lpMhqyH-9eO83zRWA',
    appId: '1:90431643782:web:9b116c50fee9e6bcb3f107',
    messagingSenderId: '90431643782',
    projectId: 'chti-face-book-a983b',
    authDomain: 'chti-face-book-a983b.firebaseapp.com',
    storageBucket: 'chti-face-book-a983b.firebasestorage.app',
  );
}
